//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.3053 版自动生成。
// 
namespace I6100SYY.qq {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://192.168.0.9/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WebService1() {
            this.Url = "http://192.168.0.9/asdf/webservice1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.0.9/getBillInfoByBillNo", RequestNamespace="http://192.168.0.9/", ResponseNamespace="http://192.168.0.9/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getBillInfoByBillNo(string BillNo) {
            object[] results = this.Invoke("getBillInfoByBillNo", new object[] {
                        BillNo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetBillInfoByBillNo(string BillNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getBillInfoByBillNo", new object[] {
                        BillNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndgetBillInfoByBillNo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.0.9/getActQtyByBillNoEntryID", RequestNamespace="http://192.168.0.9/", ResponseNamespace="http://192.168.0.9/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getActQtyByBillNoEntryID(string BillNo, string EntryID) {
            object[] results = this.Invoke("getActQtyByBillNoEntryID", new object[] {
                        BillNo,
                        EntryID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetActQtyByBillNoEntryID(string BillNo, string EntryID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getActQtyByBillNoEntryID", new object[] {
                        BillNo,
                        EntryID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetActQtyByBillNoEntryID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.0.9/insertQRCode2T_QRCode", RequestNamespace="http://192.168.0.9/", ResponseNamespace="http://192.168.0.9/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int insertQRCode2T_QRCode(string QRCode, string billNo, string EntryID) {
            object[] results = this.Invoke("insertQRCode2T_QRCode", new object[] {
                        QRCode,
                        billNo,
                        EntryID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegininsertQRCode2T_QRCode(string QRCode, string billNo, string EntryID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("insertQRCode2T_QRCode", new object[] {
                        QRCode,
                        billNo,
                        EntryID}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndinsertQRCode2T_QRCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.0.9/updateICStockByActQty", RequestNamespace="http://192.168.0.9/", ResponseNamespace="http://192.168.0.9/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int updateICStockByActQty(string billNo, string EntryID, int SuccessCount) {
            object[] results = this.Invoke("updateICStockByActQty", new object[] {
                        billNo,
                        EntryID,
                        SuccessCount});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateICStockByActQty(string billNo, string EntryID, int SuccessCount, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateICStockByActQty", new object[] {
                        billNo,
                        EntryID,
                        SuccessCount}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndupdateICStockByActQty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
}
